### ISSUE TITLE
Change svg color

### ISSUE THREAD

**Issue by stevecode21** [codefeathers/rollup-plugin-svelte-svg#15]
Is it possible to change the color(fill) of a SVG in this package?

**Comment by Iyongbudiarso** [comment]
You can add attribute `fill`, use like this

```
import IconInstagram from '../icon/instagram.svg';
...

<IconInstagram fill="red" />
```

**Comment by MKRhere** [comment]
That's indeed how you do it :) All props will be passed down to the svg element.
