### ISSUE TITLE
Error: 'target' is a required option

### ISSUE THREAD

**Issue by romdim** [codefeathers/rollup-plugin-svelte-svg#17]
I have a sapper setup and everything works fine for my SVGs in production mode following your readme but not for the dev env, which results in `Error: 'target' is a required option`.
Had to remove the dev option from within rollup in order to not get the error.
I don't know if this is relevant only to me but I thought to put it here in case someone else needs it too. You can close this issue if you cannot reproduce it.
Thanks for the plugin btw!

**Comment by MKRhere** [comment]
Sorry for the late response, but I couldn't reproduce this issue and hoped someone could add on to it. Feel free to reopen if you could create a minimal reproduction with this issue.
