### ISSUE TITLE
NPM error: EINVALIDTAGNAME when using install instructions

### ISSUE THREAD

**Issue by Fermain** [codefeathers/rollup-plugin-svelte-svg#22]
Installing plugin into a fresh Svelte template using `npm i -D`:

> npm ERR! code EINVALIDTAGNAME
> npm ERR! Invalid tag name "^3.x.y": Tags may not have any characters that encodeURIComponent encodes.

I experience the same behaviour while trying `npm i`.

**Comment by MKRhere** [comment]
Thanks, fixed in new publish
