### ISSUE TITLE
Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by Izobov** [codefeathers/rollup-plugin-svelte-svg#28]
There is an error during build.
Please change the path from (fs/promises) to (fs).promises
![image](https://user-images.githubusercontent.com/54995954/134869901-f9f19659-7867-4711-99ae-0e549b02d41e.png)

**Comment by MKRhere** [comment]
Just for clarity, are you on node 12?

**Comment by MKRhere** [comment]
Fixed in `rollup-plugin-svelte-svg@1.0.0-beta.5`

**Comment by Izobov** [comment]
Thanks. node 12.16.1
