### ISSUE TITLE
Loading module from “http://localhost:3030/static/image.svg.svelte” was blocked because of a disallowed MIME type 

### ISSUE THREAD

**Issue by Valexr** [codefeathers/rollup-plugin-svelte-svg#29]
SvelteKit booked import with `.svg.svelte` extensions...

**Comment by MKRhere** [comment]
Can you make a simple repo where I can try this out? I've not used SvelteKit before, and setting `kit.vite` seems to override SvelteKit's internal vite config and breaks all types of things.

**Comment by Valexr** [comment]
It's very simple...
Just:
- make new sveltekit project `npm init svelte@next my-app`
- add yours plugin in [svelte.config.js kit.vite section](https://kit.svelte.dev/docs#configuration)
- and try importing .svg file in `routes/index.svelte` script section, like in yours readme examples 🤷🏻‍♂️
By default assets live in `static` folder...

**Comment by MKRhere** [comment]
To import them as Svelte components, your SVG should be in `src`. Not `static`.

**Comment by Valexr** [comment]
ok
