### ISSUE TITLE
(plugin svg) Error: options.name must be a valid identifier (got 'map-pin')

### ISSUE THREAD

**Issue by ansarizafar** [codefeathers/rollup-plugin-svelte-svg#9]
I am unable to import an svg file with a hyphen in file name. I am try to import this file https://github.com/tabler/tabler-icons/blob/master/icons/map-pin.svg

**Comment by MKRhere** [comment]
Fixed in 4fc8d4bc02aab87d95c03c88dd4ef4ec2380150a / [npm version 0.2.3](https://www.npmjs.com/package/rollup-plugin-svelte-svg/v/0.2.3)
